clusterName: ""
organization: ""

userConfig:
  certManager:
    configMap:
      values: |
        # cert-manager-app v3.x.x
        # cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
        # their public IPs. Since those are not reachable from private clusters, we instead rely on the
        # recursive nameserver (for AWS, that's normally the default nameserver requested in EC2 instances).
        #
        # Without this, we get an error like
        #
        #   cert-manager/challenges "msg"="propagation check failed" "error"="dial tcp 205.251.194.0:53: i/o timeout"
        #
        # where the IP is an AWS nameserver, and DNS-over-TCP is attempted after UDP has failed before.
        #
        # For public clusters, this setting should have no effect, as they can use the HTTP01 solver.
        dns01RecursiveNameserversOnly: true
        ciliumNetworkPolicy:
          enabled: true
  externalDns:
    configMap:
      values: |
        provider: aws
        aws:
          irsa: "true"
          batchChangeInterval: null
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::{{ include "aws-account-id" $ }}:role/{{ .Values.clusterName }}-Route53Manager-Role
        domainFilters:
          - {{ .Values.baseDomain }}
        txtOwnerId: giantswarm-io-external-dns
        txtPrefix: {{ .Values.clusterName }}
        annotationFilter: giantswarm.io/external-dns=managed
        sources:
          - service
        extraArgs:
          - "--aws-batch-change-interval=10s"
  metricsServer:
    configMap:
      values: |
        ciliumNetworkPolicy:
          enabled: true
  netExporter:
    configMap:
      values: |
        NetExporter:
          NTPServers: 169.254.169.123
  observabilityBundle:
    configMap:
      values: |
        ciliumNetworkPolicy:
          enabled: true
apps:
  capi-node-labeler:
    appName: capi-node-labeler
    chartName: capi-node-labeler
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/capi-node-labeler-app
    version: 0.3.4
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    dependsOn: prometheus-operator-crd
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.8.2
  certManager:
    appName: cert-manager
    chartName: cert-manager-app
    catalog: default
    enabled: true
    clusterValues:
      configMap: true
      secret: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-manager-app
    version: 3.5.0
  chartOperatorExtensions:
    appName: chart-operator-extensions
    chartName: chart-operator-extensions
    catalog: default
    enabled: true
    clusterValues:
      configMap: false
      secret: false
    dependsOn: prometheus-operator-crd
    namespace: giantswarm
    # used by renovate
    # repo: giantswarm/chart-operator-extensions
    version: 1.1.1
  externalDns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: true
    enabled: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.42.0
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.4.1
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    dependsOn: prometheus-operator-crd
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.18.0
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.18.1
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    dependsOn: prometheus-operator-crd
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 4.2.0
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    enabled: true
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.8.9

providerSpecific:
  awsAccountId: ""
  awsClusterRoleIdentityName: ""
